services:
  postgres:
    image: postgres:17.4-alpine
    container_name: rbac-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - rbac-db-data:/var/lib/postgresql/data

volumes:
  rbac-db-data: